### PR TITLE
Add tips for setting the cql_primary_key_order

### PR DESCRIPTION
**Pull request by RyanQuey**
Just another README update, to explain in more detail how to set the `cql_primary_key_order`. I can understand if you wouldn't want to merge this, since it does make this table quite large, but I wasn't sure where else to put it, and this was tripping me up pretty badly and telling me that my PARTITION_KEY was actually type REGULAR instead, when the real problem was `cql_primary_key_order`

Side note: if I have changes should I branch off of and merge into v6.8.4-strapdata or v6.2.3-strapdata?

### CODE REVIEW

**Comment by vroyer** [comment]
In fact, cql_primary_key_order should by 0, 1, and 2 for user, post_date, id in your example.

for example, if you discover this table:
CREATE TABLE test.foo2 (
    a int,
    b text,
    c int,
    PRIMARY KEY (a, b, c)
) WITH CLUSTERING ORDER BY (b ASC, c ASC)

You get the following mapping with a discover:
"mappings" : {
      "foo2" : {
        "properties" : {
          "a" : {
            "type" : "integer",
            "cql_collection" : "singleton",
            "cql_partition_key" : true,
            "cql_primary_key_order" : 0
          },
          "b" : {
            "type" : "keyword",
            "cql_collection" : "singleton",
            "cql_primary_key_order" : 1
          },
          "c" : {
            "type" : "integer",
            "cql_collection" : "singleton",
            "cql_primary_key_order" : 2
          }
        }
      }
    },

**Comment by RyanQuey** [comment]
Oh ok, in that case maybe this is a bug instead? Maybe I set something up wrong when adding my Cassandra table? My actual table is different, but for the docs I was just using the twitter example as was done elsewhere in the docs. 

This is my schema:
```
CREATE TABLE podcast_analysis_tool.search_queries_by_term (
  term text,
  external_api text,
  search_type text,
  podcast_count int,
  result_json text,  
  updated_at timestamp,
  PRIMARY KEY (term, external_api, search_type);
```

And when I run:
```
SELECT * FROM system_schema.columns    WHERE keyspace_name = 'podcast_analysis_tool'   AND table_name = 'search_queries_by_term';
```
It returns:
image

I originally tried with `cql_primary_key_order` set as you described, and it returned this: 

image


(Ubuntu 18.04, using docker image strapdata/elassandra:6.8.4.3)

**Comment by vroyer** [comment]
Position in the CQL schema has not the same meaning than cql_primary_key_order, which is the position of the column in the primary key, starting from 0.
Another boolean attribute, cql_partition_key says if the column is a partition key or not.

**Comment by RyanQuey** [comment]
So for my composite primary key, which is `PRIMARY KEY (term, external_api, search_type)`, cql_primary_key_order should be: 

term: 0
external_api: 1
search_type: 2

correct? Then why would creating an index in ES break unless I do: 

term: 0
external_api: 0
search_type: 1

(which matches the `position` returned by calling `SELECT * FROM system_schema.columns`)

**Comment by vroyer** [comment]
Your example is correct, cql_primary_key_order and CQL position are just not the same thing.

**Pull request closed without merging**
